### ISSUE TITLE
image.tar.xz is out of LFS credits

### ISSUE THREAD

**Issue by osresearch** [pmezydlo/BeagleWire#1]
The quick start image at https://github.com/pmezydlo/BeagleWire/blob/master/load_fw/image.tar.xz is unavailable due to insufficient LFS credits.

Would you add the file as a release instead?  Github's [guide to working with large files](https://help.github.com/articles/distributing-large-binaries/) suggests that as a way to distribute large binaries and "We don't limit the total size of your binary release files, nor the bandwidth used to deliver them".

**Comment by osresearch** [comment]
Good argument for why open source projects shouldn't use LFS: https://medium.com/@megastep/github-s-large-file-storage-is-no-panacea-for-open-source-quite-the-opposite-12c0e16a9a91

> The free LFS storage tier includes 1GB of storage and just 1GB of monthly bandwidth. The bandwith amount is ridiculously low. If you have a repo with 500MB of binary assets to upload to LFS, then after your initial upload and the first download, you’d have no bandwidth left and nobody could access those files until the next billing cycle.

Since this image file is 390 MB, that is not even three downloads per month. It's incredibly frustrating that github doesn't have a way to download the individual files from LFS, so the BeagleWire image is locked away until the next cycle.

**Comment by mwelling** [comment]
I have contacted Beagleboard.org about hosting the image.

**Comment by osresearch** [comment]
I was able to upload the image as a release on my fork of the tree: https://github.com/osresearch/BeagleWire/releases/tag/20180620

**Comment by mwelling** [comment]
We also have it cached here now:
https://rcn-ee.net/rootfs/bb.org/testing/BeagleWire/

**Comment by mwelling** [comment]
Here is the sha256sum for reference (should probably be added to the documentation):
sha256sum image.tar.xz
eb862b8898b821627909952854688b46b93778fff4164c7c096453025ec7caeb  image.tar.xz

**Comment by mwelling** [comment]
@pmezydlo please add a release to your repository.

Also update the file download locations in the eLinux documentation. Once it is complete you can clear out this ticket.

**Comment by pmezydlo** [comment]
Documentation was updated. 
https://elinux.org/BeagleBoard/BeagleWire
