### ISSUE TITLE
PMOD pinout

### ISSUE THREAD

**Issue by osresearch** [pmezydlo/BeagleWire#12]
Are the PMOD connectors reversed from the "standard"?  The docs for most PMOD look like this, with pin 1 on the right side:

![image](https://user-images.githubusercontent.com/3068843/43951923-72c68f62-9c62-11e8-82be-e7cb24d7dae6.png)

The ones on the BW have pin 1 on the left side and ground/power on the right.

**Comment by osresearch** [comment]
The pinout for the BeagleWire PMOD also appears to order the pins differently:

0 | 2 | 4 | 6 | GND | VCC
--|--|--|--|--|--
1 | 3 | 5 | 7 | GND | VCC

**Comment by pmezydlo** [comment]
I'm working on fix pmod value on schematic and all pcf files. Thx for help.

pt., 10 sie 2018 o 12:34 Trammell Hudson <notifications@github.com>
napisał(a):

**Comment by pmezydlo** [comment]
We can't provide best solution for align BeagleWire pmod to Digilent Pmods. In commit I provided one solution: Connectors are aligned to Digilent Pmods but reversed by 180 degrees. 

4 | 5 | 6 | 7 | GND | VCC
0 | 1 | 2 | 3 | GND | VCC

What do you think about this solution?

commit 6f053101162bbe49a94b182ed35a59a9a23b6744 (HEAD -> master, origin/master, origin/HEAD)
Author: Patryk <mezydlo.p@gmail.com>
Date:   Sat Aug 11 17:52:12 2018 +0200

    Fix PMOD numbering. Connectors was aligning to typical PMOD numbering.
    
    Signed-off-by: Patryk <mezydlo.p@gmail.com>

**Comment by osterwood** [comment]
I ran into this issue and want my PMOD peripherals to be face up -- so I designed a two different adapter boards which only cost a few dollars at OSH Park.  CC License and posted to github here: 

https://github.com/CapableRobot/PMOD-Adapters

Note that I've NOT tested these yet (just designed them tonight) so their may be some design flaw I'm not seeing.  

Lastly, be aware that IO pin numbering is based on the PMOD standard and exits on the BeagleWire side in a form that minimized trace length & vias -- it does not match the mapping that Patryk proposed above.  If you use these boards, you'll have to adjust pin maps appropriately.

**Comment by ombhilare999** [comment]
according to this pcf file:
https://github.com/BeagleWire/BeagleWire/blob/e8fb13b11c5bcd0500af15b0671edef7c6d8c694/examples/gpio/pinmap.pcf#L55-L90

This is the pinout of PMOD:

4 | 5 | 6 | 7 | GND | VCC
|---|---|---|---|---|---|
0 | 1 | 2 | 3 | GND | VCC

I have ordered @osterwood 's breakout board for reversing the PMOD order if there is any issue with the breakout board I will reopen this thread.

Beaglewire Github Org: https://github.com/BeagleWire/BeagleWire
Docs: https://beaglewire.github.io/

regards,
Omkar Bhilare
ombhilare999@gmail.com
