### ISSUE TITLE
Which LCD used for examples/lcd_game ?

### ISSUE THREAD

**Issue by shapr** [pmezydlo/BeagleWire#13]
I'd like to purchase the LCD for the game, see how it works.
Could you add a README.md in the lcd and lcd_game directories describing where I can purchase the screen?

**Comment by pmezydlo** [comment]
Sure I can update README.md. I used AT050TN33 lcd screen.

**Comment by ombhilare999** [comment]
Since the issue was solved, I will be closing this issue.

On another note, The BeagleWire project has been resumed again.

Beaglewire Github Org: https://github.com/BeagleWire:
Docs: https://beaglewire.github.io/

regards,
Omkar Bhilare
