### ISSUE TITLE
C source for arm_blink_leds?

### ISSUE THREAD

**Issue by shapr** [pmezydlo/BeagleWire#15]
I've read much, but am still not sure how write to /dev/mem in the beaglebone to make the arm_blink_leds example work.

Could you include a C program that does the right thing?
I would be happy to write a README.md for that example if I had a program that could flip those bits!

**Comment by ombhilare999** [comment]
C source for Arm blink examples: https://github.com/BeagleWire/BeagleWire/blob/master/bridge_lib/memmap.c
Wrapper shell script: https://github.com/BeagleWire/BeagleWire/blob/master/examples/arm_blink_leds/arm_blink.sh
Docs for Arm blink examples: https://beaglewire.github.io/Examples/arm_blink_leds.html

I will be closing this thread, feel free to revert back (In case needed [complete starting guide for beaglewire](https://beaglewire.github.io/Blogs/Getting_BBB_Ready_for_BeagleWire.html)  )

regards,
Omkar Bhilare
ombhilare999@gmail.com
