### ISSUE TITLE
bad behavior in echo in examples/ Makefile.beaglewire using pre-prepared image

### ISSUE THREAD

**Issue by idcrook** [pmezydlo/BeagleWire#16]
Trying a BeagleWire today using the [pre-prepared image](https://elinux.org/BeagleBoard/BeagleWire#Use_pre-prepared_BBB_image), I noticed today that `echo` statement in https://github.com/pmezydlo/BeagleWire/blob/6f053101162bbe49a94b182ed35a59a9a23b6744/examples/Makefile.beaglewire#L25
was adding text strings instead of what I assume was intended to be NUL-character padding at the end of the _.bin_ file:

```
$ xxd blink.bin | tail -n 4
00020fa0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00020fb0: 0000 0000 0000 22fb d201 0600 2d65 205c  ......".....-e \
00020fc0: 7830 5c78 305c 7830 5c78 305c 7830 5c78  x0\x0\x0\x0\x0\x
00020fd0: 305c 7830 0a                             0\x0.
```

I have a PR with a tested fix.  https://github.com/idcrook/BeagleWire/pull/1

```
$ xxd blink.bin | tail -n 4
00020f90: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00020fa0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00020fb0: 0000 0000 0000 22fb d201 0600 0000 0000  ......".........
00020fc0: 0000 0000                                ....
```

I also added a target (`.bg-prog`) in the shared makefile in same PR to use the fpga upload wrapper that comes with the pre-prepared image, since the `.load` target did now seem to be working for me.

```bash
cd ~/BeagleWire/examples/blink_leds
make
sudo make blink.bw-prog
```

Should I submit a PR here? I am wanting to make it easier for pre-prepared image/QuickStart to use the examples, etc.

**Comment by idcrook** [comment]
I made a couple additional updates in https://github.com/idcrook/BeagleWire/pull/2 and  https://github.com/idcrook/BeagleWire/pull/3 so that the Makefile references the `/load_fw` directory at a relative path in the repository. I also included some debugability enhancements to the bw-load.sh in that PR.

I'll gladly submit a PR for these.

**Comment by pmezydlo** [comment]
Changes was merged, thanks for help.
