### ISSUE TITLE
Did the BeagleWire project die?

### ISSUE THREAD

**Issue by BJobsis** [pmezydlo/BeagleWire#19]
I see no updates in development since april 2018 . So, I suppose there are no new updates or examples (like "how to..") on te BeagleWire.
I tried for weeks to get the Wire working but without any succes. I always end up with: "fpga-load.ko not found".
I believe that when spending so much money on a BeagleBone Black and a BeagleWire it should be up and running within a few hours.

**Comment by pmezydlo** [comment]
Hi,

Looks like "fpga-load.ko" was not built.
You can do it manually by type "make" in the "load_fw" directory. (
https://github.com/pmezydlo/BeagleWire/tree/master/load_fw)

Patryk



niedz., 20 gru 2020 o 11:12 BJobsis <notifications@github.com> napisał(a):

**Comment by BJobsis** [comment]
Patryk,

Thank you for your fast response.
I'll test it as soon as I have my  BBB up and running again (I'm still
suffering getting the right image in the MMC).
Thanks again.

Have a good Christmas and a better 2021.

Barry

**Comment by BJobsis** [comment]
Patryk,

I can't get it working anymore. The burning pgm Etcher warns that
BeagleWire-image.tar.xz misses the partition table (it's only one partion
wher it should be two, as I hope to understand it well).
But I can't find anywhere another BeagleWire image. I tried for days now
and nothing works.
I used the following documents: https://elinux.org/BeagleBoard/BeagleWire
 and https://www.armhf.com/boards/beaglebone-black/bbb-sd-install/ to make
it bootable (but that didn't the trick either).

Linux is not really my knowledge area so I have to do it with what 'they'
tell me in those documents.
Do you have any suggestion (after Christmas of course).
Thanks and have a nice Christmas (as far as the Covid19 regime allows it).

regards, Barry

**Comment by BJobsis** [comment]
Patryk,

This is my last attemp to get my BeagleWire problem solved. because it took
me too much time to find a solution (it's almost 2 month I did not do
anything else but B-WIRE).
If this will not do it I assume that the BeagleWire is DEAD;also because
nothing seems to have happened since 2018. I can't find any newer hits in
Google.

Then I stop and wasted about 150 EURO on  a BBB and BeagleWire.
But positive: I learned a lot Linux commands and procs.

My last problem:
I tried to make the .ko file via the solution on:

*https://unix.stackexchange.com/questions/4638/how-to-create-ko-files-in-linux
<https://unix.stackexchange.com/questions/4638/how-to-create-ko-files-in-linux>
*

but again it gave : " implicit decleration…. Fpga_mgr_firmware…. Etc"  (see
below).

For me this is the reason why the .ko file is not created.  <==



See: https://github.com/pmezydlo/BeagleWire/blob/master/load_fw/fpga-load.c

make gives the msg: fpga-load.c:38:8: error: implicit declaration of
function ……..

ret =fpga_mgr_firmware-load…. Did you mean          fpga_mgr_load

 at statement: *ret = fpga_mgr_firmware_load(mgr, &fpga_info, path);*


Is fpga-load.c still up-to-date?


regards, Barry Jobsis

**Comment by ombhilare999** [comment]
The issue of building was due to the updates in the fpga linux driver.
They removed the `fpga_mgr_firmware_load` function and integrated that into `fpga_mgr_load`

Try the script on the following repo (Also working in hardware with commit [26a99da](https://github.com/BeagleWire/BeagleWire/commit/26a99da29026b22f7ae1b405d108799cf7eee21a) )
https://github.com/BeagleWire/BeagleWire/tree/testing 
[Complete Getting started guide for beaglewire](https://beaglewire.github.io/Blogs/Getting_BBB_Ready_for_BeagleWire.html)

Regards,
Omkar Bhilare
ombhilare999@gmail.com
