### ISSUE TITLE
Tool support

### ISSUE THREAD

**Issue by sbenyamin** [pmezydlo/BeagleWire#20]
The proposed tool set includes archne-pnr.  This tool claims to support only the 1K and 8K lattice parts of the iCE40 family. The beaglewire uses the 4K device. Can you please clarify.
Thanks

**Comment by pmezydlo** [comment]
Yes, but 4K fpgas is also supported by 8K. During work on BeagleWire I did not notice any issues related to this.

**Comment by ombhilare999** [comment]
```The ICE40HX4K is only limited to 4K LUTs via software, internally it has the same die as the 8K part - using IceStorm allows it to be used as an 8K devices.```
It won't have any issues, BeagleWire project has been resumed again. 

Beaglewire Github Org: https://github.com/BeagleWire:
Docs: https://beaglewire.github.io/
